name: 构建安卓64位APK

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-22.04


    steps:

    - name: Checkout
      uses: actions/checkout@v5


    - name: 安装依赖
      run: |

        sudo apt update

        sudo apt install -y \
          python3-pip \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake



    - name: 安装Android工具
      run: |

        yes | sdkmanager --licenses || true

        sdkmanager "platform-tools"

        sdkmanager "platforms;android-33"

        sdkmanager "build-tools;33.0.2"

        sdkmanager "ndk;25.2.9519653"



    - name: 安装Buildozer
      run: |

        python3 -m pip install --upgrade pip

        pip uninstall -y buildozer

        pip install buildozer==1.5.0

        pip install cython==0.29.37



    - name: 设置环境
      run: |

        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV

        echo "ANDROIDNDK=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV



    - name: 编译
      run: |

        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653

        buildozer -v android debug



    - name: 上传APK
      uses: actions/upload-artifact@v5

      with:

        name: apk-arm64

        path: bin/*.apk
