name: Build Android APK

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-22.04


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install system packages
      run: |

        sudo apt update

        sudo apt install -y \
          python3-pip \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake



    - name: Setup Java
      run: |

        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV



    - name: Install Android SDK tools
      run: |

        yes | sdkmanager --licenses || true

        sdkmanager "platform-tools"

        sdkmanager "platforms;android-33"

        sdkmanager "build-tools;33.0.2"

        sdkmanager "ndk;25.2.9519653"



    - name: Install Buildozer
      run: |

        python3 -m pip install --upgrade pip

        pip uninstall -y buildozer || true

        pip install buildozer==1.5.0

        pip install cython==0.29.37

        buildozer --version



    - name: Set Android NDK
      run: |

        echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/25.2.9519653" >> $GITHUB_ENV



    - name: Clean old cache
      run: |

        rm -rf .buildozer



    - name: Build APK
      run: |

        buildozer -v android debug



    - name: Upload APK
      uses: actions/upload-artifact@v4

      with:

        name: arm64-apk

        path: bin/*.apk
