name: 构建安卓APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 下载代码
        uses: actions/checkout@v4

      - name: 安装环境
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libssl-dev

          pip install --upgrade pip
          pip install --upgrade buildozer setuptools
          pip install cython==0.29.37

      - name: 编译APK
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: '1'
        run: |
          rm -rf .buildozer/
          buildozer -v android debug

      - name: 保存APK
        uses: actions/upload-artifact@v4
        with:
          name: 安卓64位APK
          path: bin/*.apk
